spring:
  application:
    name: auth-api

  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: appuser
    password: apppass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.flywaydb: INFO
    org.springframework.jdbc.datasource.init: INFO
    org.hibernate.SQL: INFO
data-api:
  base-url: 
  internal-token: 
