create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null
);

create table if not exists processing_log (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    input_text text not null,
    output_text text not null,
    created_at timestamp not null
);